"""Official TrendForce source definitions and topical filters."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PageSource:
    name: str
    module: str
    url: str
    kind: str
    access_note: str


DEFAULT_RSS_FEEDS = {
    "semianalysis": "https://www.semianalysis.com/feed",
    # Official core-company feeds that can move semiconductor / AI infrastructure supply chains.
    "openai_news": "https://openai.com/news/rss.xml",
    "nvidia_blog": "https://blogs.nvidia.com/feed/",
    "nvidia_developer_blog": "https://developer.nvidia.com/blog/feed/",
    "samsung_semiconductor_news": "https://news.samsungsemiconductor.com/global/feed/",
    "samsung_global_semiconductor": "https://news.samsung.com/global/category/products/semiconductor/feed",
    "skhynix_newsroom": "https://news.skhynix.com/feed/",
    "micron_news_releases": "https://investors.micron.com/rss/news-releases.xml",
    # TrendForce Press Centre official RSS categories.
    "trendforce_semiconductors": "https://www.trendforce.com/feed/Semiconductors.html",
    "trendforce_emerging": "https://www.trendforce.com/feed/Emerging_technology.html",
    "trendforce_consumer": "https://www.trendforce.com/feed/Consumer_electronics.html",
    "trendforce_energy": "https://www.trendforce.com/feed/Energy.html",
    "trendforce_display": "https://www.trendforce.com/feed/Display.html",
    "trendforce_led": "https://www.trendforce.com/feed/LED.html",
    "trendforce_communication": "https://www.trendforce.com/feed/Communication.html",
}


TREND_FORCE_PAGE_SOURCES: tuple[PageSource, ...] = (
    PageSource(
        "trendforce_research_latest",
        "TrendForce / Research Report / Latest",
        "https://www.trendforce.com/research",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_dram",
        "TrendForce / Research Report / Semiconductors / DRAM",
        "https://www.trendforce.com/research/category/Semiconductors/DRAM",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_nand",
        "TrendForce / Research Report / Semiconductors / NAND Flash",
        "https://www.trendforce.com/research/category/Semiconductors/NAND%20Flash",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_mlcc",
        "TrendForce / Research Report / Semiconductors / MLCC",
        "https://www.trendforce.com/research/category/Semiconductors/MLCC",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_foundry",
        "TrendForce / Research Report / Semiconductors / Wafer Foundries",
        "https://www.trendforce.com/research/category/Semiconductors/Wafer%20Foundries",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_compound",
        "TrendForce / Research Report / Semiconductors / Compound Semiconductor",
        "https://www.trendforce.com/research/category/Semiconductors/Compound%20Semiconductor",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_ai_hbm_server",
        "TrendForce / Research Report / Semiconductors / AI-HBM-Server",
        "https://www.trendforce.com/research/category/Semiconductors/AI%20Server_HBM_Server",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_cloud_edge",
        "TrendForce / Research Report / Emerging Technologies / Cloud & Edge Computing",
        "https://www.trendforce.com/research/category/Emerging%20Technologies/Cloud%20_%20Edge%20Computing",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_ai",
        "TrendForce / Research Report / Emerging Technologies / Artificial Intelligence",
        "https://www.trendforce.com/research/category/Emerging%20Technologies/Artificial%20Intelligence",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_display_supply",
        "TrendForce / Research Report / Display / Display Supply Chain",
        "https://www.trendforce.com/research/category/Display/Display%20Supply%20Chain",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_display_upstream",
        "TrendForce / Research Report / Display / Upstream Components",
        "https://www.trendforce.com/research/category/Display/Upstream%20Components",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_optical_laser",
        "TrendForce / Research Report / LED / IR LED-VCSEL-LiDAR Laser",
        "https://www.trendforce.com/research/category/LED/IR%20LED%20_%20VCSEL%20_%20LiDAR%20Laser",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_research_energy_storage",
        "TrendForce / Research Report / Energy / Lithium Battery and Energy Storage",
        "https://www.trendforce.com/research/category/Energy/Lithium%20Battery%20and%20Energy%20Storage",
        "research",
        "多为 Research Report 或会员报告；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_selected_semiconductors",
        "TrendForce / Selected Topics / Semiconductors",
        "https://www.trendforce.com/research/category/selected_topics/tri_semiconductors",
        "selected_topics",
        "Selected Topics 多为会员/专题内容；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_selected_telecom",
        "TrendForce / Selected Topics / Telecommunications",
        "https://www.trendforce.com/research/category/selected_topics/tri_telecommunications",
        "selected_topics",
        "Selected Topics 多为会员/专题内容；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_selected_computer_system",
        "TrendForce / Selected Topics / Computer System",
        "https://www.trendforce.com/research/category/selected_topics/computer_system",
        "selected_topics",
        "Selected Topics 多为会员/专题内容；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_selected_greenenergy",
        "TrendForce / Selected Topics / Green Energy and Storage",
        "https://www.trendforce.com/research/category/selected_topics/greenenergy_and_storage",
        "selected_topics",
        "Selected Topics 多为会员/专题内容；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_selected_display_led",
        "TrendForce / Selected Topics / Display Panel and LED",
        "https://www.trendforce.com/research/category/selected_topics/display_panel_and_led",
        "selected_topics",
        "Selected Topics 多为会员/专题内容；当前只监控官方列表页公开标题/摘要，不绕过付费墙。",
    ),
    PageSource(
        "trendforce_press_analysis",
        "TrendForce / Press Centre / In-Depth Analyses",
        "https://www.trendforce.com/presscenter/analysis",
        "press_analysis",
        "免费/付费状态取决于原文页面；当前入口来自 TrendForce Press Centre 官方列表。",
    ),
)


FOCUS_KEYWORDS = (
    "semiconductor",
    "chip",
    "foundry",
    "fab",
    "wafer",
    "tsmc",
    "samsung",
    "intel",
    "nvidia",
    "amd",
    "broadcom",
    "asic",
    "gpu",
    "accelerator",
    "advanced packaging",
    "packaging",
    "cowos",
    "copos",
    "foplp",
    "glass core",
    "substrate",
    "pcb",
    "materials",
    "equipment",
    "lithography",
    "etch",
    "deposition",
    "memory",
    "dram",
    "nand",
    "nor flash",
    "hbm",
    "ssd",
    "mlcc",
    "capacitor",
    "passive component",
    "cpo",
    "npo",
    "optical",
    "photonics",
    "silicon photonics",
    "laser",
    "dfb",
    "vcsel",
    "inp",
    "fiber",
    "transceiver",
    "ai",
    "artificial intelligence",
    "llm",
    "large language model",
    "openai",
    "anthropic",
    "deepseek",
    "agentic",
    "inference",
    "training",
    "server",
    "data center",
    "datacenter",
    "cloud",
    "edge computing",
    "power",
    "electricity",
    "energy storage",
    "battery",
    "grid",
    "cooling",
    "thermal",
    "liquid cooling",
    "cooling",
    "rubin",
    "blackwell",
    "gb300",
    "nvlink",
    "cuda",
    "networking",
    "ethernet",
    "infiniband",
    "sovereign ai",
    "tpu",
    "claude",
    "gpt",
    "openai",
    "anthropic",
    "micron",
    "sk hynix",
    "skhynix",
    "diamond",
    "synthetic diamond",
    "artificial diamond",
    "lab-grown diamond",
    "diamond substrate",
    "diamond heat spreader",
    "diamond cooling",
    "半导体",
    "芯片",
    "晶圆",
    "封装",
    "玻璃基板",
    "金刚石",
    "人造钻石",
    "培育钻石",
    "单晶金刚石",
    "多晶金刚石",
    "金刚石衬底",
    "金刚石散热",
    "钻石散热",
    "光模块",
    "光通信",
    "激光",
    "内存",
    "存储",
    "大模型",
    "数据中心",
    "电力",
    "液冷",
    "散热",
    "英伟达",
    "三星电子",
    "海力士",
    "美光",
    "智谱",
)


def is_focus_item(*parts: str) -> bool:
    text = " ".join(part for part in parts if part).lower()
    return any(keyword in text for keyword in FOCUS_KEYWORDS)
