#!/usr/bin/env python3
"""Fetch a mihomo subscription and force local-only proxy settings."""

from __future__ import annotations

import os
import re
import urllib.request
from pathlib import Path


PROXY_DIR = Path(os.getenv("SURVEIL_PROXY_DIR", "/opt/surveil-proxy"))
SUBSCRIPTION_PATH = PROXY_DIR / "subscription.url"
CONFIG_PATH = PROXY_DIR / "config.yaml"


def fetch_subscription(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "surveil-mihomo-config/0.1",
            "Accept": "text/yaml, text/plain, */*",
        },
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8", errors="replace")


def strip_top_level_keys(config: str, keys: tuple[str, ...]) -> str:
    lines = config.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    out: list[str] = []
    skip = False
    key_pattern = re.compile(r"^([A-Za-z0-9_-]+)\s*:")
    keys_set = set(keys)
    for line in lines:
        top_level = bool(line) and not line.startswith((" ", "\t", "-"))
        if top_level:
            match = key_pattern.match(line)
            skip = bool(match and match.group(1) in keys_set)
        if not skip:
            out.append(line)
    return "\n".join(out).strip() + "\n"


def first_proxy_group_name(config: str) -> str:
    in_groups = False
    pending_item = False
    for line in config.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        if line.startswith("proxy-groups:"):
            in_groups = True
            continue
        if in_groups and line and not line.startswith((" ", "\t", "-")):
            break
        if in_groups:
            if re.match(r"\s*-\s*$", line):
                pending_item = True
                continue
            match = re.match(r"\s*-\s+name\s*:\s*(.+?)\s*$", line)
            if not match and pending_item:
                match = re.match(r"\s+name\s*:\s*(.+?)\s*$", line)
            if match:
                value = match.group(1).strip().strip('"').strip("'")
                if value:
                    return value
            if pending_item and line.strip() and not re.match(r"\s+name\s*:", line):
                pending_item = False
    return "DIRECT"


def build_local_only_config(raw_config: str) -> str:
    default_group = first_proxy_group_name(raw_config)
    cleaned = strip_top_level_keys(
        raw_config,
        (
            "dns",
            "mixed-port",
            "redir-port",
            "tproxy-port",
            "port",
            "socks-port",
            "allow-lan",
            "bind-address",
            "external-controller",
            "external-ui",
            "secret",
            "ipv6",
            "rules",
        ),
    )
    header = """# Generated by scripts/update_mihomo_config.py. Do not edit manually.
mixed-port: 7890
allow-lan: false
bind-address: 127.0.0.1
ipv6: false
external-controller: 127.0.0.1:9090

"""
    return header + cleaned + f"\nrules:\n  - MATCH,{default_group}\n"


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Fetch or sanitize a mihomo/clash subscription config.")
    parser.add_argument("--input", default="", help="Use an existing subscription YAML file instead of fetching subscription.url.")
    parser.add_argument("--output", default=str(CONFIG_PATH), help="Output mihomo config path.")
    args = parser.parse_args()

    PROXY_DIR.mkdir(parents=True, exist_ok=True)
    if args.input:
        raw_config = Path(args.input).read_text(encoding="utf-8")
    else:
        if not SUBSCRIPTION_PATH.exists():
            raise SystemExit(f"缺少订阅链接文件：{SUBSCRIPTION_PATH}")
        subscription_url = SUBSCRIPTION_PATH.read_text(encoding="utf-8").strip()
        if not subscription_url:
            raise SystemExit(f"订阅链接为空：{SUBSCRIPTION_PATH}")
        raw_config = fetch_subscription(subscription_url)
    if "proxies:" not in raw_config and "proxy-providers:" not in raw_config:
        raise SystemExit("订阅内容不像 mihomo/clash YAML：缺少 proxies 或 proxy-providers")
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_local_only_config(raw_config), encoding="utf-8")
    output_path.chmod(0o600)
    print(f"已更新 {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
